[supervisord]
nodaemon=true

[program:vnc]
command=/usr/bin/x11vnc -display :0 -forever -usepw -create
autostart=true
autorestart=true
stderr_logfile=/var/log/vnc.err.log
stdout_logfile=/var/log/vnc.out.log

[program:novnc]
command=/usr/local/bin/noVNC/utils/launch.sh --vnc localhost:5900
autostart=true
autorestart=true
stderr_logfile=/var/log/novnc.err.log
stdout_logfile=/var/log/novnc.out.log
